#!/usr/bin/perl

use strict;

use List::Util qw(sum);
use Data::Dumper;
use File::Basename;
use Cwd 'abs_path';
my $script_dir = dirname(abs_path($0));
my $common_dir = dirname($script_dir);
require "$common_dir/common.pl";

my $JAVADB_PATH = "/usr/share/javadb";

$| = 1;
set_system_echo();

system_or_die("rm -rf $script_dir/TESTDB");
system_or_die("$JAVADB_PATH/bin/ij $script_dir/createdb_derby.sql");
system_or_die("$JAVADB_PATH/bin/ij $script_dir/createtable_derby.sql");
system_or_die("$JAVADB_PATH/bin/ij $script_dir/createproc_derby.sql");
