#!/usr/bin/perl

use strict;

use Getopt::Std;
use File::Basename;
use Cwd 'abs_path';
my $script_dir = dirname(abs_path($0));
my $common_dir = dirname($script_dir);
require "$common_dir/common.pl";

my $JAVADB_PATH = "/usr/share/javadb";
my $DOTS_PATH = $ENV{HOME} . "/Dots";
my $LOG_PATH = "/tmp/dots/results/nonfuse";
my $DERBY_CONFIG = "derby.ini";

our ($opt_f);
getopts('f');
if($opt_f) {
	$DERBY_CONFIG = "derbyfuse.ini";
	$LOG_PATH = "/tmp/dots/results/fuse";
}

my $case = shift;
my $iterations = shift;

$| = 1;
set_system_echo();

system_or_die("mkdir -p $LOG_PATH");
system_or_die("rm -rf $LOG_PATH/*");
my $CLASSPATH = "$JAVADB_PATH/lib/derby.jar:$DOTS_PATH/Dots.jar";
#exec_or_die("java -cp $CLASSPATH dots.framework.Dots -config $script_dir/$DERBY_CONFIG -case $case");
for(1 .. $iterations) {
	system_or_die("java -cp $CLASSPATH dots.framework.Dots -config $script_dir/$DERBY_CONFIG -case $case");
}
