#!/usr/bin/perl

use strict;

use List::Util qw(sum);
use Data::Dumper;
use File::Basename;
use Cwd 'abs_path';
my $script_dir = dirname(abs_path($0));
my $common_dir = dirname($script_dir);
require "$common_dir/common.pl";

my $DOTS_PATH = $ENV{HOME} . "/Dots";
my $port = 8001;

$| = 1;
set_system_echo();

my $CLASSPATH = "$DOTS_PATH/Perfmon.jar";
exec_or_die("java -cp $CLASSPATH dots.perfmon.PerfMon -port $port");
