#!/bin/bash

MASTER_NODE=dfnode-0
SPARK_PATH=${HOME}/spark
SPARK_SUBMIT=${SPARK_PATH}/bin/spark-submit
SCRIPT=${HOME}/spark/examples/src/main/python/pi.py

sudo rm -rf /mnt/test/spark/results
#${SPARK_PATH}/sbin/stop-all.sh
#${SPARK_PATH}/sbin/start-all.sh

   #--master yarn \
time $SPARK_SUBMIT \
   --master spark://${MASTER_NODE}:7077 \
   $SCRIPT 2000
