#!/bin/bash

LIBPATH=/users/lembkej/defuse/lddefuse/liblddefuse.so
fusermount -u /tmp/fuse

for i in {1..50}
do
	#rm -f /mnt/test/open.o
	#LD_PRELOAD=${LIBPATH} ./mytime ./testdfstat
	#./mytime ./teststat
	../../fuse/fusexmp /tmp/fuse
	./mytime ./testfusestat
	fusermount -u /tmp/fuse
done
