#!/bin/bash

LIBPATH=/users/lembkej/defuse/lddefuse/liblddefuse.so
fusermount -u /tmp/fuse

for i in {1..50}
do
	rm -f /mnt/test/test*
	./testcreate
	#LD_PRELOAD=${LIBPATH} ./mytime ./testdfunlink
	#./mytime ./testunlink
	../../fuse/fusexmp /tmp/fuse
	./mytime ./testfuseunlink
	fusermount -u /tmp/fuse
done
