#!/bin/bash

sudo umount /tmp/tmpdir
#sudo umount ~/proxytest;
#sudo umount ~/proxytest2; 

sudo rmmod proxyfs; 
sudo insmod proxyfs.ko; 

sudo mount -t proxyfs -o backend=/tmp/tmpb /dev/null /tmp/tmpdir
#sudo mount -t proxyfs -o backend=~/pbe /dev/null ~/proxytest
#sudo mount -t proxyfs -o backend=~/pbe /dev/null ~/proxytest2
#sudo mount -t proxyfs -o backend=~/proxytest2 /dev/null ~/proxytest
