#!/usr/bin/perl

use strict;

use File::Basename;
use Cwd 'abs_path';
my $defuse_dir = dirname(dirname(dirname(abs_path($0))));
require "$defuse_dir/test/common.pl";

my $mountfuse = "/users/" . $ENV{USER} . "/Projects/defuse/test/hadoop/mountfuse";
my $resethadooptmp = "/users/" . $ENV{USER} . "/Projects/defuse/test/hadoop/resethadooptmp";

set_system_echo();

my @compute_nodes = (
	'dfnode-0.defuse.rosco.isi.deterlab.net',
	'dfnode-1.defuse.rosco.isi.deterlab.net',
	'dfnode-2.defuse.rosco.isi.deterlab.net',
	'dfnode-3.defuse.rosco.isi.deterlab.net',
	'dfnode-4.defuse.rosco.isi.deterlab.net',
);
=pub
my @compute_nodes = (
	'10.1.1.4',
	'10.1.1.5',
	'10.1.1.6',
	'10.1.1.7',
	'10.1.1.8',
);
=cut

for(@compute_nodes) {
	system_or_die("ssh $_ $mountfuse");
	system_or_die("ssh $_ $resethadooptmp");
}
