#!/usr/bin/perl

use strict;

use File::Basename;
use Cwd 'abs_path';
my $defuse_dir = dirname(dirname(dirname(abs_path($0))));
require "$defuse_dir/test/common.pl";

set_system_echo();

my $user = $ENV{USER};
my $hadoop_tmp_dir = "/mnt/hadoop-$user/nm-local-dir/";
system_or_die("rm -rf $hadoop_tmp_dir/*");
