#!/usr/bin/perl

use strict;

use File::Basename;
use Cwd 'abs_path';
my $defuse_dir = dirname(dirname(dirname(abs_path($0))));
require "$defuse_dir/test/common.pl";

set_system_echo();

my $user = $ENV{USER};
my $hadoop_root = "/mnt/hadoop-$user/";
my $hadoop_tmp = "$hadoop_root/nm-local-dir";
my $hadoop_dfs = "$hadoop_root/dfs";
my $hadoop_dfs_data = "$hadoop_dfs/data";

# Delete old data
system_or_die("sudo rm -rf $hadoop_root");
system_or_die("sudo rm -rf /mnt/test/hadoop-$user");

# Reset tmp space
system_or_die("sudo mkdir -p $hadoop_tmp");
system_or_die("sudo chown $user.users $hadoop_root");
system_or_die("sudo chown $user.users $hadoop_tmp");

#Reset hadoop storage
system_or_die("sudo mkdir -p $hadoop_dfs_data");
system_or_die("sudo chown $user.users $hadoop_dfs_data");
