#!/bin/bash

HADOOP_VERSION=2.9.1
HADOOP_PATH="${HOME}/hadoop-${HADOOP_VERSION}"
YARN_BIN="${HADOOP_PATH}/bin/yarn"
HADOOP_MRLIB="${HADOOP_PATH}/share/hadoop/mapreduce/hadoop-mapreduce-examples-${HADOOP_VERSION}.jar"

$YARN_BIN jar $HADOOP_MRLIB $1 $2 $3 $4 $5 
